-- Main script with user configuration

DROP DATABASE IF EXISTS :CONFIGURE_DBNAME;
CREATE DATABASE :CONFIGURE_DBNAME;

-- Create user (no need in strong password, server has no privilegies)
REASSIGN OWNED BY :CONFIGURE_SERVERUSER TO postgres;
DROP OWNED BY :CONFIGURE_SERVERUSER;
DROP USER IF EXISTS :CONFIGURE_SERVERUSER;
CREATE USER :CONFIGURE_SERVERUSER WITH PASSWORD 'serv_auth_password';

-- Remove server user privilegies
REVOKE ALL ON SCHEMA public FROM public;
REVOKE ALL ON DATABASE :CONFIGURE_DBNAME FROM :CONFIGURE_SERVERUSER;

-- Grant basic permissions for working
GRANT USAGE ON SCHEMA public TO :CONFIGURE_SERVERUSER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO :CONFIGURE_SERVERUSER;

-- Grand CRUD on common tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :CONFIGURE_SERVERUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :CONFIGURE_SERVERUSER;
