-- Main script with user configuration

-- Add server user privilegies
GRANT USAGE ON SCHEMA detector  TO :CONFIGURE_SERVERUSER;
GRANT USAGE ON SCHEMA versions  TO :CONFIGURE_SERVERUSER;
GRANT USAGE ON SCHEMA etc       TO :CONFIGURE_SERVERUSER;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA detector TO :CONFIGURE_SERVERUSER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA versions TO :CONFIGURE_SERVERUSER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA etc      TO :CONFIGURE_SERVERUSER;

-- Grand CRUD on schemas
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA detector TO :CONFIGURE_SERVERUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA detector
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :CONFIGURE_SERVERUSER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA versions TO :CONFIGURE_SERVERUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA versions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :CONFIGURE_SERVERUSER;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA etc TO :CONFIGURE_SERVERUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA etc
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :CONFIGURE_SERVERUSER;
